<?php
/**
 * @category    Fishpig
 * @package     Fishpig_AttributeSplash
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($this->canDisplay()): ?>
	<?php if ($this->displaySplashPagesTogether()): ?>
		<?php $splashPages = $this->getAllSplashPages() ?>
		<?php $pageCount = count($splashPages) ?>
		<?php if ($pageCount > 0): ?>
			<li class="level0 nav-<?php echo 1 + $this->getCategoryIndexOffset() ?> level-top parent">
				<a href="#" class="level-top"><span><?php echo $this->escapeHtml($this->getGroupedTitle()) ?></span></a>
				<ul class="level0">
				<?php $pageIt = 1 ?>
				<?php foreach($splashPages as $splashPage): ?>
					<li class="level1 nav-<?php echo 1 + $this->getCategoryIndexOffset() ?>-<?php echo $pageIt ?><?php if ($pageIt == 1): ?> first<?php endif; ?><?php if ($pageIt == $pageCount): ?> last<?php endif; ?>">
						<a href="<?php echo $splashPage->getUrl() ?>" title="<?php echo $this->escapeHtml($splashPage->getName()) ?>"><span><?php echo $this->escapeHtml($splashPage->getName()) ?></span></a>
					</li>
				<?php ++$pageIt; endforeach; ?>
				</ul>
			</li>
		<?php endif; ?>
	<?php else: ?>
		<?php $splashGroups = $this->getSplashGroups() ?>
		<?php $groupCount = count($splashGroups) ?>
		<?php if ($groupCount > 0): ?>
		<?php $sub_brandid = 0 ?>
			<?php $groupIt = 1 ?>
			<?php foreach($splashGroups as $splashGroup): ?>
				<?php /* ?><li class="level0 nav-<?php echo $groupIt + $this->getCategoryIndexOffset() ?> level-top parent">
					<a href="<?php echo $splashGroup->canDisplay() ? $splashGroup->getUrl() : '#' ?>" class="level-top"><span><?php echo $this->escapeHtml($splashGroup->getName()) ?></span></a> <?php */ ?>
					<?php $splashPages = $this->getSplashGroupSplashPages($splashGroup) ?>
					<?php $pageCount = count($splashPages) ?>
					<?php $pageIt = 1; ?>
					<?php if ($pageCount > 0): ?>
						<ul class="sub-brand" id=<?php echo '"id_sub-brand'.$sub_brandid.'"';?>>
						<?php foreach($splashPages as $splashPage): ?>
							<li>
								<a href="<?php echo $splashPage->getUrl() ?>" title="<?php echo $this->escapeHtml($splashPage->getName()) ?>"  class="line-h"><?php echo $this->escapeHtml($splashPage->getName()) ?></a>
							</li>
						<?php ++$pageIt; endforeach; ?>
						<?php if ($sub_brandid==1): ?>	
							<li> <a class="line-h-inspiracao" id="id_inspiracao_link" title="Inspire-se" style="color:#d99b1a; font-weight:bold"  href="/inspire-se" >Inspire-se</a></li>
							<?php $sub_brandid = $sub_brandid +1; ?>
						<?php endif; ?>
						</ul>
					<?php endif; ?>
				<?php /* ?></li><?php */ ?>
			<?php $sub_brandid = $sub_brandid +1; ?>
			<?php ++$groupIt; endforeach; ?>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>
